version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_cerba
    environment:
      POSTGRES_DB: cerba_interview_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Th1s1sMyPass_word
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
